<Global.Microsoft.VisualBasic.CompilerServices.DesignerGenerated()> _
Partial Class MainMenuList
    Inherits System.Windows.Forms.Form

    'Form 覆寫 Dispose 以清除元件清單。
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    '為 Windows Form 設計工具的必要項
    Private components As System.ComponentModel.IContainer

    '注意: 以下為 Windows Form 設計工具所需的程序
    '可以使用 Windows Form 設計工具進行修改。
    '請不要使用程式碼編輯器進行修改。
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container
        Dim TreeNode1 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("帳號管理", 4, 4)
        Dim TreeNode2 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("更新U_p2重量", 4, 4)
        Dim TreeNode3 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("Test", 4, 4)
        Dim TreeNode4 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("新增排程", 4, 4)
        Dim TreeNode5 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("修改排程", 4, 4)
        Dim TreeNode6 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢排程", 4, 4)
        Dim TreeNode7 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產排程", New System.Windows.Forms.TreeNode() {TreeNode4, TreeNode5, TreeNode6})
        Dim TreeNode8 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("快速訂單", 4, 4)
        Dim TreeNode9 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("入庫", 4, 4)
        Dim TreeNode10 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("出庫", 4, 4)
        Dim TreeNode11 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("由PDA同步", New System.Windows.Forms.TreeNode() {TreeNode9, TreeNode10})
        Dim TreeNode12 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("日報表週排", 4, 4)
        Dim TreeNode13 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("電宰BOM", 4, 4)
        Dim TreeNode14 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("現場工時預估記錄表", 4, 4)
        Dim TreeNode15 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產需求計算", 4, 4)
        Dim TreeNode16 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("EC出貨表單列印", 4, 4)
        Dim TreeNode17 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("EC宅配單列印", 4, 4)
        Dim TreeNode18 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("EC存貨領用待申請清單", 4, 4)
        Dim TreeNode19 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("EC進價維護", 4, 4)
        Dim TreeNode20 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("EC進價覆核", 4, 4)
        Dim TreeNode21 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("EC進價維護", New System.Windows.Forms.TreeNode() {TreeNode19, TreeNode20})
        Dim TreeNode22 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("員購價維護", 4, 4)
        Dim TreeNode23 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("員購價覆核", 4, 4)
        Dim TreeNode24 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("員購價維護", New System.Windows.Forms.TreeNode() {TreeNode22, TreeNode23})
        Dim TreeNode25 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產入庫_New", 4, 4)
        Dim TreeNode26 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("PDA入庫", 4, 4)
        Dim TreeNode27 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("暫無用程式", New System.Windows.Forms.TreeNode() {TreeNode2, TreeNode3, TreeNode7, TreeNode8, TreeNode11, TreeNode12, TreeNode13, TreeNode14, TreeNode15, TreeNode16, TreeNode17, TreeNode18, TreeNode21, TreeNode24, TreeNode25, TreeNode26})
        Dim TreeNode28 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("管理", New System.Windows.Forms.TreeNode() {TreeNode1, TreeNode27})
        Dim TreeNode29 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("訂單輸入", 4, 4)
        Dim TreeNode30 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("訂單輸入2", 4, 4)
        Dim TreeNode31 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("訂單上傳作業", 4, 4)
        Dim TreeNode32 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("訂單上傳統計(好市多)", 4, 4)
        Dim TreeNode33 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("訂單基礎資料", 4, 4)
        Dim TreeNode34 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("快速回傳B1", 4, 4)
        Dim TreeNode35 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("外部人員基本資料維護", 4, 4)
        Dim TreeNode36 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("年度銷售預估商品簡稱對應表", 4, 4)
        Dim TreeNode37 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("年度銷售預估客戶群組對應表", 4, 4)
        Dim TreeNode38 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("雞隻使用換算表", 4, 4)
        Dim TreeNode39 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("年度銷售量(週預估)-客戶規劃", 4, 4)
        Dim TreeNode40 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("年度銷售量(週預估)-排程規劃", 4, 4)
        Dim TreeNode41 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("年度銷售量預估(申請)", 4, 4)
        Dim TreeNode42 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("年度銷售量預估(批核)", 4, 4)
        Dim TreeNode43 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("年度銷售量(月預估)", 4, 4)
        Dim TreeNode44 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("訂單作業", New System.Windows.Forms.TreeNode() {TreeNode29, TreeNode30, TreeNode31, TreeNode32, TreeNode33, TreeNode34, TreeNode35, TreeNode36, TreeNode37, TreeNode38, TreeNode39, TreeNode40, TreeNode41, TreeNode42, TreeNode43})
        Dim TreeNode45 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("發票作業", 4, 4)
        Dim TreeNode46 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("退貨作業", 4, 4)
        Dim TreeNode47 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("變價作業", 4, 4)
        Dim TreeNode48 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("回收單作業", 4, 4)
        Dim TreeNode49 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("回收單修改", 4, 4)
        Dim TreeNode50 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("調整單作業", 4, 4)
        Dim TreeNode51 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("調整單修改", 4, 4)
        Dim TreeNode52 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("報表查詢列印", 4, 4)
        Dim TreeNode53 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("空籃作業", New System.Windows.Forms.TreeNode() {TreeNode48, TreeNode49, TreeNode50, TreeNode51, TreeNode52})
        Dim TreeNode54 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("司機業績表", 4, 4)
        Dim TreeNode55 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("業務業績獎金表", 4, 4)
        Dim TreeNode56 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("業績獎金表", New System.Windows.Forms.TreeNode() {TreeNode54, TreeNode55})
        Dim TreeNode57 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("新增契養批號", 4, 4)
        Dim TreeNode58 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("契養結算", 4, 4)
        Dim TreeNode59 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("契養報表", 4, 4)
        Dim TreeNode60 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("製單契養批單", 4, 4)
        Dim TreeNode61 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("維護契養資料", 4, 4)
        Dim TreeNode62 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("預計抓雞牧場", 4, 4)
        Dim TreeNode63 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("毛雞供應量預估表", 4, 4)
        Dim TreeNode64 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("契養作業", New System.Windows.Forms.TreeNode() {TreeNode57, TreeNode58, TreeNode59, TreeNode60, TreeNode61, TreeNode62, TreeNode63})
        Dim TreeNode65 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("交貨單明細表", 4, 4)
        Dim TreeNode66 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("時段排程比對", 4, 4)
        Dim TreeNode67 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("出貨單查詢(交貨草稿)", 4, 4)
        Dim TreeNode68 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢", New System.Windows.Forms.TreeNode() {TreeNode65, TreeNode66, TreeNode67})
        Dim TreeNode69 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("預估排程作業", 4, 4)
        Dim TreeNode70 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("預估數量", 4, 4)
        Dim TreeNode71 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("預估訂單數量", 4, 4)
        Dim TreeNode72 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("預估排程", New System.Windows.Forms.TreeNode() {TreeNode69, TreeNode70, TreeNode71})
        Dim TreeNode73 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("單據重量列印", 4, 4)
        Dim TreeNode74 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("營業", 2, 2, New System.Windows.Forms.TreeNode() {TreeNode44, TreeNode45, TreeNode46, TreeNode47, TreeNode53, TreeNode56, TreeNode64, TreeNode68, TreeNode72, TreeNode73})
        Dim TreeNode75 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("現場生產排程單", 4, 4)
        Dim TreeNode76 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("現場排程基本資料", 4, 4)
        Dim TreeNode77 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("排程總表", 4, 4)
        Dim TreeNode78 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產需求統計", 4, 4)
        Dim TreeNode79 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("訂單轉排程", 4, 4)
        Dim TreeNode80 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("日排轉排程", 4, 4)
        Dim TreeNode81 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("銷售預估雞隻需求(週)", 4, 4)
        Dim TreeNode82 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("比對表", 4, 4)
        Dim TreeNode83 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產需求設定", 4, 4)
        Dim TreeNode84 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("線上撿貨", 4, 4)
        Dim TreeNode85 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產排程", New System.Windows.Forms.TreeNode() {TreeNode75, TreeNode76, TreeNode77, TreeNode78, TreeNode79, TreeNode80, TreeNode81, TreeNode82, TreeNode83, TreeNode84})
        Dim TreeNode86 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢生產訂單", 4, 4)
        Dim TreeNode87 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("快速新增生產訂單", 4, 4)
        Dim TreeNode88 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("快速回填生產訂單", 4, 4)
        Dim TreeNode89 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產訂單", New System.Windows.Forms.TreeNode() {TreeNode86, TreeNode87, TreeNode88})
        Dim TreeNode90 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢領料單", 4, 4)
        Dim TreeNode91 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢領料單-依製單", 4, 4)
        Dim TreeNode92 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("快速新增預領單", 4, 4)
        Dim TreeNode93 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("排程領料單", 4, 4)
        Dim TreeNode94 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("分時領料單_核准", 4, 4)
        Dim TreeNode95 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("領料單", New System.Windows.Forms.TreeNode() {TreeNode90, TreeNode91, TreeNode92, TreeNode93, TreeNode94})
        Dim TreeNode96 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("委外代工生產明細回存", 4, 4)
        Dim TreeNode97 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("委外代工分析領料單", 4, 4)
        Dim TreeNode98 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("委外代工", New System.Windows.Forms.TreeNode() {TreeNode96, TreeNode97})
        Dim TreeNode99 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢產出率明細表", 4, 4)
        Dim TreeNode100 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢化製/飼料明細表", 4, 4)
        Dim TreeNode101 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("依條碼查產品明細資料", 4, 4)
        Dim TreeNode102 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("加工原料肉領料單查詢列印", 4, 4)
        Dim TreeNode103 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("產程明細表", 4, 4)
        Dim TreeNode104 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("冷藏貨庫存查詢表", 4, 4)
        Dim TreeNode105 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢報表", New System.Windows.Forms.TreeNode() {TreeNode99, TreeNode100, TreeNode101, TreeNode102, TreeNode103, TreeNode104})
        Dim TreeNode106 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("日報表新增", 4, 4)
        Dim TreeNode107 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("日報表修改", 4, 4)
        Dim TreeNode108 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("日報表查詢", 4, 4)
        Dim TreeNode109 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("單價修改", 4, 4)
        Dim TreeNode110 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("毛雞預估查詢", 4, 4)
        Dim TreeNode111 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("毛雞運輸", New System.Windows.Forms.TreeNode() {TreeNode106, TreeNode107, TreeNode108, TreeNode109, TreeNode110})
        Dim TreeNode112 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("領料查詢", 4, 4)
        Dim TreeNode113 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產需求計算", 4, 4)
        Dim TreeNode114 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("製程基本標準", 4, 4)
        Dim TreeNode115 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("加工過磅設定", 4, 4)
        Dim TreeNode116 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("加工作業", New System.Windows.Forms.TreeNode() {TreeNode112, TreeNode113, TreeNode114, TreeNode115})
        Dim TreeNode117 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產入庫比對", 4, 4)
        Dim TreeNode118 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("時段排程比對", 4, 4)
        Dim TreeNode119 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("即時產成查詢", 4, 4)
        Dim TreeNode120 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產比對", New System.Windows.Forms.TreeNode() {TreeNode117, TreeNode118, TreeNode119})
        Dim TreeNode121 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("屠宰記錄", 4, 4)
        Dim TreeNode122 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("記錄", New System.Windows.Forms.TreeNode() {TreeNode121})
        Dim TreeNode123 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("分級槽基礎存編設定", 4, 4)
        Dim TreeNode124 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("分級槽基礎存編設定_新", 4, 4)
        Dim TreeNode125 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("現場機台過磅設定", 4, 4)
        Dim TreeNode126 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("磅秤設定", New System.Windows.Forms.TreeNode() {TreeNode123, TreeNode124, TreeNode125})
        Dim TreeNode127 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生管", New System.Windows.Forms.TreeNode() {TreeNode85, TreeNode89, TreeNode95, TreeNode98, TreeNode105, TreeNode111, TreeNode116, TreeNode120, TreeNode122, TreeNode126})
        Dim TreeNode128 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("入庫", 4, 4)
        Dim TreeNode129 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("出庫", 4, 4)
        Dim TreeNode130 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("由Excel同步", New System.Windows.Forms.TreeNode() {TreeNode128, TreeNode129})
        Dim TreeNode131 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("同步作業", New System.Windows.Forms.TreeNode() {TreeNode130})
        Dim TreeNode132 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("入庫自動化", 4, 4)
        Dim TreeNode133 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產入庫", 4, 4)
        Dim TreeNode134 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("電宰製單入庫", 4, 4)
        Dim TreeNode135 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("特殊入庫", 4, 4)
        Dim TreeNode136 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("採購入庫", 4, 4)
        Dim TreeNode137 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("採購入庫_鮮享作業", 4, 4)
        Dim TreeNode138 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("退貨入庫", 4, 4)
        Dim TreeNode139 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("入庫", New System.Windows.Forms.TreeNode() {TreeNode132, TreeNode133, TreeNode134, TreeNode135, TreeNode136, TreeNode137, TreeNode138})
        Dim TreeNode140 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("出庫作業", 4, 4)
        Dim TreeNode141 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("毛雞發貨", 4, 4)
        Dim TreeNode142 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("出庫作業_New", 4, 4)
        Dim TreeNode143 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("出庫", New System.Windows.Forms.TreeNode() {TreeNode140, TreeNode141, TreeNode142})
        Dim TreeNode144 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("出庫作業_New2", 4, 4)
        Dim TreeNode145 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產單快速入出庫", 4, 4)
        Dim TreeNode146 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("單據入庫作業", 4, 4)
        Dim TreeNode147 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("單據重量列印", 4, 4)
        Dim TreeNode148 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("回傳B1", New System.Windows.Forms.TreeNode() {TreeNode139, TreeNode143, TreeNode144, TreeNode145, TreeNode146, TreeNode147})
        Dim TreeNode149 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("派工查詢", 4, 4)
        Dim TreeNode150 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("分時領料", 4, 4)
        Dim TreeNode151 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("分時領料單", 4, 4)
        Dim TreeNode152 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("出急速庫作業", 4, 4)
        Dim TreeNode153 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("派工作業", New System.Windows.Forms.TreeNode() {TreeNode149, TreeNode150, TreeNode151, TreeNode152})
        Dim TreeNode154 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("條碼儲位變更", 4, 4)
        Dim TreeNode155 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("整批儲位變更", 4, 4)
        Dim TreeNode156 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("儲位變更查詢", 4, 4)
        Dim TreeNode157 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢儲位條碼調庫記錄", 4, 4)
        Dim TreeNode158 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢目前儲位狀況", 4, 4)
        Dim TreeNode159 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("調庫作業", 4, 4)
        Dim TreeNode160 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("儲位基本資料維護")
        Dim TreeNode161 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("儲位管理", New System.Windows.Forms.TreeNode() {TreeNode154, TreeNode155, TreeNode156, TreeNode157, TreeNode158, TreeNode159, TreeNode160})
        Dim TreeNode162 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("序號交易報表查詢", 4, 4)
        Dim TreeNode163 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("條碼庫存查詢", 4, 4)
        Dim TreeNode164 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("依條碼查產品明細資料", 4, 4)
        Dim TreeNode165 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("指定入庫查詢表", 4, 4)
        Dim TreeNode166 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("指定入庫建議儲位查詢", 4, 4)
        Dim TreeNode167 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("由草稿查詢條碼儲位", 4, 4)
        Dim TreeNode168 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("條碼查詢", New System.Windows.Forms.TreeNode() {TreeNode162, TreeNode163, TreeNode164, TreeNode165, TreeNode166, TreeNode167})
        Dim TreeNode169 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("單張列印", 4, 4)
        Dim TreeNode170 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("批次列印", 4, 4)
        Dim TreeNode171 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("列印作業", New System.Windows.Forms.TreeNode() {TreeNode169, TreeNode170})
        Dim TreeNode172 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產單狀態", 4, 4)
        Dim TreeNode173 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("條碼狀態", 4, 4)
        Dim TreeNode174 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產入庫比對", 4, 4)
        Dim TreeNode175 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產單明細", 4, 4)
        Dim TreeNode176 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("時段排程比對", 4, 4)
        Dim TreeNode177 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("製單查詢", New System.Windows.Forms.TreeNode() {TreeNode172, TreeNode173, TreeNode174, TreeNode175, TreeNode176})
        Dim TreeNode178 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("期末存貨報表", 4, 4)
        Dim TreeNode179 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("期末存貨報表", New System.Windows.Forms.TreeNode() {TreeNode178})
        Dim TreeNode180 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("快速新增預領單", 4, 4)
        Dim TreeNode181 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("派工單", 4, 4)
        Dim TreeNode182 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("排程領料單", 4, 4)
        Dim TreeNode183 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("領料單", New System.Windows.Forms.TreeNode() {TreeNode180, TreeNode181, TreeNode182})
        Dim TreeNode184 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("冷凍品出庫查詢", 4, 4)
        Dim TreeNode185 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode(" 現有序號生鮮品(區分庫位)-G備註", 4, 4)
        Dim TreeNode186 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查庫位品項", 4, 4)
        Dim TreeNode187 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢出庫資料", 4, 4)
        Dim TreeNode188 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("交貨單轉出與轉入", 4, 4)
        Dim TreeNode189 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("採購草稿單入庫轉入", 4, 4)
        Dim TreeNode190 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("代工轉入生產", 4, 4)
        Dim TreeNode191 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("驗收/領料/加工庫存查詢", 4, 4)
        Dim TreeNode192 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("查詢報表", New System.Windows.Forms.TreeNode() {TreeNode184, TreeNode185, TreeNode186, TreeNode187, TreeNode188, TreeNode189, TreeNode190, TreeNode191})
        Dim TreeNode193 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("倉儲記錄", 4, 4)
        Dim TreeNode194 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("倉儲記錄2", 4, 4)
        Dim TreeNode195 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("記錄", New System.Windows.Forms.TreeNode() {TreeNode193, TreeNode194})
        Dim TreeNode196 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("倉庫", New System.Windows.Forms.TreeNode() {TreeNode131, TreeNode148, TreeNode153, TreeNode161, TreeNode168, TreeNode171, TreeNode177, TreeNode179, TreeNode183, TreeNode192, TreeNode195})
        Dim TreeNode197 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("會科餘額明細", 4, 4)
        Dim TreeNode198 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("進銷存", 4, 4)
        Dim TreeNode199 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("分錄核對", 4, 4)
        Dim TreeNode200 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("會科報表", 4, 4)
        Dim TreeNode201 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("比較表", 4, 4)
        Dim TreeNode202 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("關貿請款", 4, 4)
        Dim TreeNode203 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("總分類帳", 4, 4)
        Dim TreeNode204 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("利潤中心報表", 4, 4)
        Dim TreeNode205 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("發票作廢作業", 4, 4)
        Dim TreeNode206 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("發票比對", 4, 4)
        Dim TreeNode207 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("會計", New System.Windows.Forms.TreeNode() {TreeNode197, TreeNode198, TreeNode199, TreeNode200, TreeNode201, TreeNode202, TreeNode203, TreeNode204, TreeNode205, TreeNode206})
        Dim TreeNode208 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("付款申請單", 4, 4)
        Dim TreeNode209 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("快速新增採購草稿", 4, 4)
        Dim TreeNode210 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("採購歷史資料查詢", 4, 4)
        Dim TreeNode211 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("毛雞訂購單", 4, 4)
        Dim TreeNode212 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("採購", New System.Windows.Forms.TreeNode() {TreeNode208, TreeNode209, TreeNode210, TreeNode211})
        Dim TreeNode213 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("屠宰記錄", 4, 4)
        Dim TreeNode214 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產", New System.Windows.Forms.TreeNode() {TreeNode213})
        Dim TreeNode215 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("倉儲記錄", 4, 4)
        Dim TreeNode216 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("倉儲記錄2", 4, 4)
        Dim TreeNode217 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("倉庫", New System.Windows.Forms.TreeNode() {TreeNode215, TreeNode216})
        Dim TreeNode218 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("記錄", New System.Windows.Forms.TreeNode() {TreeNode214, TreeNode217})
        Dim TreeNode219 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("存貨領用申請列表", 4, 4)
        Dim TreeNode220 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("員購訂單總務覆核", 4, 4)
        Dim TreeNode221 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("電話記錄", 4, 4)
        Dim TreeNode222 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("存領單查詢", 4, 4)
        Dim TreeNode223 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("通用", New System.Windows.Forms.TreeNode() {TreeNode219, TreeNode220, TreeNode221, TreeNode222})
        Dim TreeNode224 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("訂單自動比對", 4, 4)
        Dim TreeNode225 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("倉庫", New System.Windows.Forms.TreeNode() {TreeNode224})
        Dim TreeNode226 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生產排程", 4, 4)
        Dim TreeNode227 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("計件資料", 4, 4)
        Dim TreeNode228 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("磅秤品項設定", 4, 4)
        Dim TreeNode229 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("現場磅秤資訊", 4, 4)
        Dim TreeNode230 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("時段排程比對", 4, 4)
        Dim TreeNode231 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("產程明細表", 4, 4)
        Dim TreeNode232 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("排程總表", 4, 4)
        Dim TreeNode233 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("生管", New System.Windows.Forms.TreeNode() {TreeNode226, TreeNode227, TreeNode228, TreeNode229, TreeNode230, TreeNode231, TreeNode232})
        Dim TreeNode234 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("薪資計算", 4, 4)
        Dim TreeNode235 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("工時統計", 4, 4)
        Dim TreeNode236 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("薪資", New System.Windows.Forms.TreeNode() {TreeNode234, TreeNode235})
        Dim TreeNode237 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("退貨記錄", 4, 4)
        Dim TreeNode238 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("檢查記錄", 4, 4)
        Dim TreeNode239 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("退貨統計", 4, 4)
        Dim TreeNode240 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("品管", New System.Windows.Forms.TreeNode() {TreeNode237, TreeNode238, TreeNode239})
        Dim TreeNode241 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("日報表新增", 4, 4)
        Dim TreeNode242 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("日報表修改", 4, 4)
        Dim TreeNode243 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("日報表查詢", 4, 4)
        Dim TreeNode244 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("契養", New System.Windows.Forms.TreeNode() {TreeNode241, TreeNode242, TreeNode243})
        Dim TreeNode245 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("健檢數據資料", 4, 4)
        Dim TreeNode246 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("職安", New System.Windows.Forms.TreeNode() {TreeNode245})
        Dim TreeNode247 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("內部系統", New System.Windows.Forms.TreeNode() {TreeNode223, TreeNode225, TreeNode233, TreeNode236, TreeNode240, TreeNode244, TreeNode246})
        Dim TreeNode248 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("過磅基本設定", 4, 4)
        Dim TreeNode249 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("基本設定", New System.Windows.Forms.TreeNode() {TreeNode248})
        Dim TreeNode250 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("員購訂單", 4, 4)
        Dim TreeNode251 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("褔利社", New System.Windows.Forms.TreeNode() {TreeNode249, TreeNode250})
        Dim TreeNode252 As System.Windows.Forms.TreeNode = New System.Windows.Forms.TreeNode("變更密碼", 4, 4)
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(MainMenuList))
        Me.CompanyName = New System.Windows.Forms.Label
        Me.UserName = New System.Windows.Forms.Label
        Me.GroupBox1 = New System.Windows.Forms.GroupBox
        Me.參數區 = New System.Windows.Forms.GroupBox
        Me.Button1 = New System.Windows.Forms.Button
        Me.La時間 = New System.Windows.Forms.Label
        Me.提醒時間2 = New System.Windows.Forms.Label
        Me.提醒時間s = New System.Windows.Forms.Label
        Me.lbVersion2 = New System.Windows.Forms.Label
        Me.MenuTree = New System.Windows.Forms.TreeView
        Me.ImageList1 = New System.Windows.Forms.ImageList(Me.components)
        Me.Timer1 = New System.Windows.Forms.Timer(Me.components)
        Me.CompanyDB = New System.Windows.Forms.Label
        Me.DBSr = New System.Windows.Forms.Label
        Me.UserName2 = New System.Windows.Forms.Label
        Me.UserUnit = New System.Windows.Forms.Label
        Me.待入庫數提醒時間 = New System.Windows.Forms.Timer(Me.components)
        Me.電話提醒時間 = New System.Windows.Forms.Timer(Me.components)
        Me.待入庫數提醒 = New PopupNotifier
        Me.電話提醒畫面 = New PopupNotifier
        Me.即時時間 = New System.Windows.Forms.Timer(Me.components)
        Me.Ck提醒 = New System.Windows.Forms.CheckBox
        Me.GroupBox1.SuspendLayout()
        Me.參數區.SuspendLayout()
        Me.SuspendLayout()
        '
        'CompanyName
        '
        Me.CompanyName.AutoSize = True
        Me.CompanyName.Font = New System.Drawing.Font("新細明體", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(136, Byte))
        Me.CompanyName.Location = New System.Drawing.Point(12, 9)
        Me.CompanyName.Name = "CompanyName"
        Me.CompanyName.Size = New System.Drawing.Size(106, 16)
        Me.CompanyName.TabIndex = 0
        Me.CompanyName.Text = "CompanyName"
        '
        'UserName
        '
        Me.UserName.AutoSize = True
        Me.UserName.Font = New System.Drawing.Font("新細明體", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(136, Byte))
        Me.UserName.Location = New System.Drawing.Point(12, 34)
        Me.UserName.Name = "UserName"
        Me.UserName.Size = New System.Drawing.Size(74, 16)
        Me.UserName.TabIndex = 1
        Me.UserName.Text = "UserName"
        '
        'GroupBox1
        '
        Me.GroupBox1.Controls.Add(Me.參數區)
        Me.GroupBox1.Controls.Add(Me.lbVersion2)
        Me.GroupBox1.Controls.Add(Me.MenuTree)
        Me.GroupBox1.Dock = System.Windows.Forms.DockStyle.Bottom
        Me.GroupBox1.Location = New System.Drawing.Point(0, 71)
        Me.GroupBox1.Name = "GroupBox1"
        Me.GroupBox1.Size = New System.Drawing.Size(292, 424)
        Me.GroupBox1.TabIndex = 3
        Me.GroupBox1.TabStop = False
        '
        '參數區
        '
        Me.參數區.Controls.Add(Me.Button1)
        Me.參數區.Controls.Add(Me.La時間)
        Me.參數區.Controls.Add(Me.提醒時間2)
        Me.參數區.Controls.Add(Me.提醒時間s)
        Me.參數區.Location = New System.Drawing.Point(80, 312)
        Me.參數區.Name = "參數區"
        Me.參數區.Size = New System.Drawing.Size(200, 100)
        Me.參數區.TabIndex = 14
        Me.參數區.TabStop = False
        Me.參數區.Text = "參數區"
        Me.參數區.Visible = False
        '
        'Button1
        '
        Me.Button1.Location = New System.Drawing.Point(7, 66)
        Me.Button1.Name = "Button1"
        Me.Button1.Size = New System.Drawing.Size(75, 23)
        Me.Button1.TabIndex = 3
        Me.Button1.Text = "Button1"
        Me.Button1.UseVisualStyleBackColor = True
        '
        'La時間
        '
        Me.La時間.AutoSize = True
        Me.La時間.Location = New System.Drawing.Point(7, 50)
        Me.La時間.Name = "La時間"
        Me.La時間.Size = New System.Drawing.Size(32, 12)
        Me.La時間.TabIndex = 2
        Me.La時間.Text = "時間:"
        '
        '提醒時間2
        '
        Me.提醒時間2.AutoSize = True
        Me.提醒時間2.Location = New System.Drawing.Point(7, 34)
        Me.提醒時間2.Name = "提醒時間2"
        Me.提醒時間2.Size = New System.Drawing.Size(57, 12)
        Me.提醒時間2.TabIndex = 1
        Me.提醒時間2.Text = "提醒時間s"
        '
        '提醒時間s
        '
        Me.提醒時間s.AutoSize = True
        Me.提醒時間s.Location = New System.Drawing.Point(7, 22)
        Me.提醒時間s.Name = "提醒時間s"
        Me.提醒時間s.Size = New System.Drawing.Size(57, 12)
        Me.提醒時間s.TabIndex = 0
        Me.提醒時間s.Text = "提醒時間s"
        '
        'lbVersion2
        '
        Me.lbVersion2.AutoSize = True
        Me.lbVersion2.Font = New System.Drawing.Font("新細明體", 9.75!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(136, Byte))
        Me.lbVersion2.Location = New System.Drawing.Point(151, 2)
        Me.lbVersion2.Name = "lbVersion2"
        Me.lbVersion2.Size = New System.Drawing.Size(33, 13)
        Me.lbVersion2.TabIndex = 11
        Me.lbVersion2.Text = "時間"
        '
        'MenuTree
        '
        Me.MenuTree.BackColor = System.Drawing.Color.White
        Me.MenuTree.Dock = System.Windows.Forms.DockStyle.Fill
        Me.MenuTree.Font = New System.Drawing.Font("新細明體", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(136, Byte))
        Me.MenuTree.FullRowSelect = True
        Me.MenuTree.ImageIndex = 2
        Me.MenuTree.ImageList = Me.ImageList1
        Me.MenuTree.Location = New System.Drawing.Point(3, 18)
        Me.MenuTree.Name = "MenuTree"
        TreeNode1.BackColor = System.Drawing.Color.White
        TreeNode1.ForeColor = System.Drawing.Color.Black
        TreeNode1.ImageIndex = 4
        TreeNode1.Name = "IDMgn"
        TreeNode1.SelectedImageIndex = 4
        TreeNode1.Text = "帳號管理"
        TreeNode2.ImageIndex = 4
        TreeNode2.Name = "UP2Mgn"
        TreeNode2.SelectedImageIndex = 4
        TreeNode2.Text = "更新U_p2重量"
        TreeNode3.ImageIndex = 4
        TreeNode3.Name = "Test"
        TreeNode3.SelectedImageIndex = 4
        TreeNode3.Text = "Test"
        TreeNode4.ImageIndex = 4
        TreeNode4.Name = "AddSchedule"
        TreeNode4.SelectedImageIndex = 4
        TreeNode4.Text = "新增排程"
        TreeNode5.ImageIndex = 4
        TreeNode5.Name = "UpdateSchedule"
        TreeNode5.SelectedImageIndex = 4
        TreeNode5.Text = "修改排程"
        TreeNode6.ImageIndex = 4
        TreeNode6.Name = "QuerySchedule"
        TreeNode6.SelectedImageIndex = 4
        TreeNode6.Text = "查詢排程"
        TreeNode7.Name = "Node1"
        TreeNode7.Text = "生產排程"
        TreeNode8.BackColor = System.Drawing.Color.White
        TreeNode8.ForeColor = System.Drawing.Color.Black
        TreeNode8.ImageIndex = 4
        TreeNode8.Name = "OQUT"
        TreeNode8.SelectedImageIndex = 4
        TreeNode8.Text = "快速訂單"
        TreeNode9.ImageIndex = 4
        TreeNode9.Name = "SyncInByPDA"
        TreeNode9.SelectedImageIndex = 4
        TreeNode9.Text = "入庫"
        TreeNode10.ImageIndex = 4
        TreeNode10.Name = "SyncOutByPDA"
        TreeNode10.SelectedImageIndex = 4
        TreeNode10.Text = "出庫"
        TreeNode11.Name = "GroupC_1_PDA"
        TreeNode11.Text = "由PDA同步"
        TreeNode12.BackColor = System.Drawing.Color.White
        TreeNode12.ForeColor = System.Drawing.Color.Black
        TreeNode12.ImageIndex = 4
        TreeNode12.Name = "OCWscheduling"
        TreeNode12.SelectedImageIndex = 4
        TreeNode12.Text = "日報表週排"
        TreeNode13.ImageIndex = 4
        TreeNode13.Name = "電宰BOM"
        TreeNode13.SelectedImageIndex = 4
        TreeNode13.Text = "電宰BOM"
        TreeNode14.ImageIndex = 4
        TreeNode14.Name = "Whours"
        TreeNode14.SelectedImageIndex = 4
        TreeNode14.Text = "現場工時預估記錄表"
        TreeNode15.ImageIndex = 4
        TreeNode15.Name = "生產需求計算"
        TreeNode15.SelectedImageIndex = 4
        TreeNode15.Text = "生產需求計算"
        TreeNode16.ImageIndex = 4
        TreeNode16.Name = "EC出貨表單列印"
        TreeNode16.SelectedImageIndex = 4
        TreeNode16.Text = "EC出貨表單列印"
        TreeNode17.ImageIndex = 4
        TreeNode17.Name = "EC宅配單列印"
        TreeNode17.SelectedImageIndex = 4
        TreeNode17.Text = "EC宅配單列印"
        TreeNode18.ImageIndex = 4
        TreeNode18.Name = "EC存貨領用待申請清單"
        TreeNode18.SelectedImageIndex = 4
        TreeNode18.Text = "EC存貨領用待申請清單"
        TreeNode19.ImageIndex = 4
        TreeNode19.Name = "EC進價維護"
        TreeNode19.SelectedImageIndex = 4
        TreeNode19.Text = "EC進價維護"
        TreeNode20.ImageIndex = 4
        TreeNode20.Name = "EC進價覆核"
        TreeNode20.SelectedImageIndex = 4
        TreeNode20.Text = "EC進價覆核"
        TreeNode21.Name = "Node0"
        TreeNode21.Text = "EC進價維護"
        TreeNode22.ImageIndex = 4
        TreeNode22.Name = "員購價維護"
        TreeNode22.SelectedImageIndex = 4
        TreeNode22.Text = "員購價維護"
        TreeNode23.ImageIndex = 4
        TreeNode23.Name = "員購價覆核"
        TreeNode23.SelectedImageIndex = 4
        TreeNode23.Text = "員購價覆核"
        TreeNode24.Name = "員購價維護"
        TreeNode24.Text = "員購價維護"
        TreeNode25.ImageIndex = 4
        TreeNode25.Name = "生產入庫"
        TreeNode25.SelectedImageIndex = 4
        TreeNode25.Text = "生產入庫_New"
        TreeNode26.ImageIndex = 4
        TreeNode26.Name = "SyncInByPDA"
        TreeNode26.SelectedImageIndex = 4
        TreeNode26.Text = "PDA入庫"
        TreeNode27.Name = "暫無用程式"
        TreeNode27.Text = "暫無用程式"
        TreeNode28.BackColor = System.Drawing.Color.White
        TreeNode28.ForeColor = System.Drawing.Color.Black
        TreeNode28.Name = "GroupMan"
        TreeNode28.Text = "管理"
        TreeNode29.BackColor = System.Drawing.Color.White
        TreeNode29.ForeColor = System.Drawing.Color.Black
        TreeNode29.ImageIndex = 4
        TreeNode29.Name = "ORDR"
        TreeNode29.SelectedImageIndex = 4
        TreeNode29.Text = "訂單輸入"
        TreeNode30.ImageIndex = 4
        TreeNode30.Name = "訂單輸入2"
        TreeNode30.SelectedImageIndex = 4
        TreeNode30.Text = "訂單輸入2"
        TreeNode31.ImageIndex = 4
        TreeNode31.Name = "訂單上傳作業"
        TreeNode31.SelectedImageIndex = 4
        TreeNode31.Text = "訂單上傳作業"
        TreeNode32.ImageIndex = 4
        TreeNode32.Name = "訂單上傳統計"
        TreeNode32.SelectedImageIndex = 4
        TreeNode32.Text = "訂單上傳統計(好市多)"
        TreeNode33.ImageIndex = 4
        TreeNode33.Name = "客戶品項"
        TreeNode33.SelectedImageIndex = 4
        TreeNode33.Text = "訂單基礎資料"
        TreeNode34.ImageIndex = 4
        TreeNode34.Name = "快速回傳B1"
        TreeNode34.SelectedImageIndex = 4
        TreeNode34.Text = "快速回傳B1"
        TreeNode35.ImageIndex = 4
        TreeNode35.Name = "外部人員基本資料維護"
        TreeNode35.SelectedImageIndex = 4
        TreeNode35.Text = "外部人員基本資料維護"
        TreeNode36.ImageIndex = 4
        TreeNode36.Name = "Node0"
        TreeNode36.SelectedImageIndex = 4
        TreeNode36.Text = "年度銷售預估商品簡稱對應表"
        TreeNode37.ImageIndex = 4
        TreeNode37.Name = "Node1"
        TreeNode37.SelectedImageIndex = 4
        TreeNode37.Text = "年度銷售預估客戶群組對應表"
        TreeNode38.ImageIndex = 4
        TreeNode38.Name = "Node2"
        TreeNode38.SelectedImageIndex = 4
        TreeNode38.Text = "雞隻使用換算表"
        TreeNode39.ImageIndex = 4
        TreeNode39.Name = "Node3"
        TreeNode39.SelectedImageIndex = 4
        TreeNode39.Text = "年度銷售量(週預估)-客戶規劃"
        TreeNode40.ImageIndex = 4
        TreeNode40.Name = "Node4"
        TreeNode40.SelectedImageIndex = 4
        TreeNode40.Text = "年度銷售量(週預估)-排程規劃"
        TreeNode41.ImageIndex = 4
        TreeNode41.Name = "Node12"
        TreeNode41.SelectedImageIndex = 4
        TreeNode41.Text = "年度銷售量預估(申請)"
        TreeNode42.ImageIndex = 4
        TreeNode42.Name = "Node13"
        TreeNode42.SelectedImageIndex = 4
        TreeNode42.Text = "年度銷售量預估(批核)"
        TreeNode43.ImageIndex = 4
        TreeNode43.Name = "Node14"
        TreeNode43.SelectedImageIndex = 4
        TreeNode43.Text = "年度銷售量(月預估)"
        TreeNode44.Name = "Node2"
        TreeNode44.Text = "訂單作業"
        TreeNode45.ImageIndex = 4
        TreeNode45.Name = "發票作業"
        TreeNode45.SelectedImageIndex = 4
        TreeNode45.Text = "發票作業"
        TreeNode46.ImageIndex = 4
        TreeNode46.Name = "退貨作業"
        TreeNode46.SelectedImageIndex = 4
        TreeNode46.Text = "退貨作業"
        TreeNode47.ImageIndex = 4
        TreeNode47.Name = "變價作業"
        TreeNode47.SelectedImageIndex = 4
        TreeNode47.Text = "變價作業"
        TreeNode48.ImageIndex = 4
        TreeNode48.Name = "AddEBin"
        TreeNode48.SelectedImageIndex = 4
        TreeNode48.Text = "回收單作業"
        TreeNode49.ImageIndex = 4
        TreeNode49.Name = "UpdateEBin"
        TreeNode49.SelectedImageIndex = 4
        TreeNode49.Text = "回收單修改"
        TreeNode50.ImageIndex = 4
        TreeNode50.Name = "AddEBadjust"
        TreeNode50.SelectedImageIndex = 4
        TreeNode50.Text = "調整單作業"
        TreeNode51.ImageIndex = 4
        TreeNode51.Name = "UpdateEBadjust"
        TreeNode51.SelectedImageIndex = 4
        TreeNode51.Text = "調整單修改"
        TreeNode52.ImageIndex = 4
        TreeNode52.Name = "QueryEB"
        TreeNode52.SelectedImageIndex = 4
        TreeNode52.Text = "報表查詢列印"
        TreeNode53.Name = "GroupA_1"
        TreeNode53.Text = "空籃作業"
        TreeNode54.ImageIndex = 4
        TreeNode54.Name = "DriversFee"
        TreeNode54.SelectedImageIndex = 4
        TreeNode54.Text = "司機業績表"
        TreeNode55.ImageIndex = 4
        TreeNode55.Name = "SalesFee"
        TreeNode55.SelectedImageIndex = 4
        TreeNode55.Text = "業務業績獎金表"
        TreeNode56.Name = "GroupA_2"
        TreeNode56.Text = "業績獎金表"
        TreeNode57.ImageIndex = 4
        TreeNode57.Name = "ContractFarms"
        TreeNode57.SelectedImageIndex = 4
        TreeNode57.Text = "新增契養批號"
        TreeNode58.ImageIndex = 4
        TreeNode58.Name = "ContractSettlement"
        TreeNode58.SelectedImageIndex = 4
        TreeNode58.Text = "契養結算"
        TreeNode59.ImageIndex = 4
        TreeNode59.Name = "FdCkSettle"
        TreeNode59.SelectedImageIndex = 4
        TreeNode59.Text = "契養報表"
        TreeNode60.ImageIndex = 4
        TreeNode60.Name = "製單契養批單"
        TreeNode60.SelectedImageIndex = 4
        TreeNode60.Text = "製單契養批單"
        TreeNode61.ImageIndex = 4
        TreeNode61.Name = "Node5"
        TreeNode61.SelectedImageIndex = 4
        TreeNode61.Text = "維護契養資料"
        TreeNode62.ImageIndex = 4
        TreeNode62.Name = "Node6"
        TreeNode62.SelectedImageIndex = 4
        TreeNode62.Text = "預計抓雞牧場"
        TreeNode63.ImageIndex = 4
        TreeNode63.Name = "Node7"
        TreeNode63.SelectedImageIndex = 4
        TreeNode63.Text = "毛雞供應量預估表"
        TreeNode64.Name = "GroupA_3"
        TreeNode64.Text = "契養作業"
        TreeNode65.ImageIndex = 4
        TreeNode65.Name = "QueryODLN"
        TreeNode65.SelectedImageIndex = 4
        TreeNode65.Text = "交貨單明細表"
        TreeNode66.ImageIndex = 4
        TreeNode66.Name = "時段排程比對_營業"
        TreeNode66.SelectedImageIndex = 4
        TreeNode66.Text = "時段排程比對"
        TreeNode67.ImageIndex = 4
        TreeNode67.Name = "出貨單查詢(交貨草稿)"
        TreeNode67.SelectedImageIndex = 4
        TreeNode67.Text = "出貨單查詢(交貨草稿)"
        TreeNode68.Name = "GroupA_4"
        TreeNode68.Text = "查詢"
        TreeNode69.ImageIndex = 4
        TreeNode69.Name = "Scheduling"
        TreeNode69.SelectedImageIndex = 4
        TreeNode69.Text = "預估排程作業"
        TreeNode70.ImageIndex = 4
        TreeNode70.Name = "預估數量"
        TreeNode70.SelectedImageIndex = 4
        TreeNode70.Text = "預估數量"
        TreeNode71.ImageIndex = 4
        TreeNode71.Name = "預估訂單數量"
        TreeNode71.SelectedImageIndex = 4
        TreeNode71.Text = "預估訂單數量"
        TreeNode72.Name = "GroupA_5"
        TreeNode72.Text = "預估排程"
        TreeNode73.ImageIndex = 4
        TreeNode73.Name = "單據重量列印"
        TreeNode73.SelectedImageIndex = 4
        TreeNode73.Text = "單據重量列印"
        TreeNode74.BackColor = System.Drawing.Color.White
        TreeNode74.ForeColor = System.Drawing.Color.Black
        TreeNode74.ImageIndex = 2
        TreeNode74.Name = "GroupA"
        TreeNode74.SelectedImageIndex = 2
        TreeNode74.Text = "營業"
        TreeNode75.ImageIndex = 4
        TreeNode75.Name = "OrderPicking"
        TreeNode75.SelectedImageIndex = 4
        TreeNode75.Text = "現場生產排程單"
        TreeNode76.ImageIndex = 4
        TreeNode76.Name = "OSPdata"
        TreeNode76.SelectedImageIndex = 4
        TreeNode76.Text = "現場排程基本資料"
        TreeNode77.ImageIndex = 4
        TreeNode77.Name = "排程總表"
        TreeNode77.SelectedImageIndex = 4
        TreeNode77.Text = "排程總表"
        TreeNode78.ImageIndex = 4
        TreeNode78.Name = "生產需求統計"
        TreeNode78.SelectedImageIndex = 4
        TreeNode78.Text = "生產需求統計"
        TreeNode79.ImageIndex = 4
        TreeNode79.Name = "訂單轉排程"
        TreeNode79.SelectedImageIndex = 4
        TreeNode79.Text = "訂單轉排程"
        TreeNode80.ImageIndex = 4
        TreeNode80.Name = "日排轉排程"
        TreeNode80.SelectedImageIndex = 4
        TreeNode80.Text = "日排轉排程"
        TreeNode81.ImageIndex = 4
        TreeNode81.Name = "Node8"
        TreeNode81.SelectedImageIndex = 4
        TreeNode81.Text = "銷售預估雞隻需求(週)"
        TreeNode82.ImageIndex = 4
        TreeNode82.Name = "比對表_v100"
        TreeNode82.SelectedImageIndex = 4
        TreeNode82.Text = "比對表"
        TreeNode83.ImageIndex = 4
        TreeNode83.Name = "生產需求設定"
        TreeNode83.SelectedImageIndex = 4
        TreeNode83.Text = "生產需求設定"
        TreeNode84.ImageIndex = 4
        TreeNode84.Name = "線上撿貨"
        TreeNode84.SelectedImageIndex = 4
        TreeNode84.Text = "線上撿貨"
        TreeNode85.Name = "GroupB_0"
        TreeNode85.Text = "生產排程"
        TreeNode86.BackColor = System.Drawing.Color.White
        TreeNode86.ForeColor = System.Drawing.Color.Black
        TreeNode86.ImageIndex = 4
        TreeNode86.Name = "QueryORDR"
        TreeNode86.SelectedImageIndex = 4
        TreeNode86.Text = "查詢生產訂單"
        TreeNode87.BackColor = System.Drawing.Color.White
        TreeNode87.ForeColor = System.Drawing.Color.Black
        TreeNode87.ImageIndex = 4
        TreeNode87.Name = "QuickAddOWOR"
        TreeNode87.SelectedImageIndex = 4
        TreeNode87.Text = "快速新增生產訂單"
        TreeNode88.BackColor = System.Drawing.Color.White
        TreeNode88.ForeColor = System.Drawing.Color.Black
        TreeNode88.ImageIndex = 4
        TreeNode88.Name = "QuickUpdateOWOR"
        TreeNode88.SelectedImageIndex = 4
        TreeNode88.Text = "快速回填生產訂單"
        TreeNode89.BackColor = System.Drawing.Color.White
        TreeNode89.ForeColor = System.Drawing.Color.Black
        TreeNode89.Name = "GroupB_1"
        TreeNode89.Text = "生產訂單"
        TreeNode90.BackColor = System.Drawing.Color.White
        TreeNode90.ForeColor = System.Drawing.Color.Black
        TreeNode90.ImageIndex = 4
        TreeNode90.Name = "QueryOIGE"
        TreeNode90.SelectedImageIndex = 4
        TreeNode90.Text = "查詢領料單"
        TreeNode91.ImageIndex = 4
        TreeNode91.Name = "QueryOIGEByU_CK02"
        TreeNode91.SelectedImageIndex = 4
        TreeNode91.Text = "查詢領料單-依製單"
        TreeNode92.BackColor = System.Drawing.Color.White
        TreeNode92.ForeColor = System.Drawing.Color.Black
        TreeNode92.ImageIndex = 4
        TreeNode92.Name = "QuickAddOIGE"
        TreeNode92.SelectedImageIndex = 4
        TreeNode92.Text = "快速新增預領單"
        TreeNode93.ImageIndex = 4
        TreeNode93.Name = "QuickAddOIGEv3"
        TreeNode93.SelectedImageIndex = 4
        TreeNode93.Text = "排程領料單"
        TreeNode94.ImageIndex = 4
        TreeNode94.Name = "分時領料單_生管"
        TreeNode94.SelectedImageIndex = 4
        TreeNode94.Text = "分時領料單_核准"
        TreeNode95.BackColor = System.Drawing.Color.White
        TreeNode95.ForeColor = System.Drawing.Color.Black
        TreeNode95.Name = "GroupB_2"
        TreeNode95.Text = "領料單"
        TreeNode96.BackColor = System.Drawing.Color.White
        TreeNode96.ForeColor = System.Drawing.Color.Black
        TreeNode96.ImageIndex = 4
        TreeNode96.Name = "AddFinishItem"
        TreeNode96.SelectedImageIndex = 4
        TreeNode96.Text = "委外代工生產明細回存"
        TreeNode97.BackColor = System.Drawing.Color.White
        TreeNode97.ForeColor = System.Drawing.Color.Black
        TreeNode97.ImageIndex = 4
        TreeNode97.Name = "QueryOutside"
        TreeNode97.SelectedImageIndex = 4
        TreeNode97.Text = "委外代工分析領料單"
        TreeNode98.BackColor = System.Drawing.Color.White
        TreeNode98.ForeColor = System.Drawing.Color.Black
        TreeNode98.Name = "GroupB_3"
        TreeNode98.Text = "委外代工"
        TreeNode99.BackColor = System.Drawing.Color.White
        TreeNode99.ForeColor = System.Drawing.Color.Black
        TreeNode99.ImageIndex = 4
        TreeNode99.Name = "CalcThroughput"
        TreeNode99.SelectedImageIndex = 4
        TreeNode99.Text = "查詢產出率明細表"
        TreeNode100.BackColor = System.Drawing.Color.White
        TreeNode100.ForeColor = System.Drawing.Color.Black
        TreeNode100.ImageIndex = 4
        TreeNode100.Name = "CalcMelts"
        TreeNode100.SelectedImageIndex = 4
        TreeNode100.Text = "查詢化製/飼料明細表"
        TreeNode101.ForeColor = System.Drawing.Color.Black
        TreeNode101.ImageIndex = 4
        TreeNode101.Name = "QuerySRNDetail"
        TreeNode101.SelectedImageIndex = 4
        TreeNode101.Text = "依條碼查產品明細資料"
        TreeNode102.ImageIndex = 4
        TreeNode102.Name = "加工原料肉領料單"
        TreeNode102.SelectedImageIndex = 4
        TreeNode102.Text = "加工原料肉領料單查詢列印"
        TreeNode103.ImageIndex = 4
        TreeNode103.Name = "產程明細表"
        TreeNode103.SelectedImageIndex = 4
        TreeNode103.Text = "產程明細表"
        TreeNode104.ImageIndex = 4
        TreeNode104.Name = "冷藏貨庫存查詢表"
        TreeNode104.SelectedImageIndex = 4
        TreeNode104.Text = "冷藏貨庫存查詢表"
        TreeNode105.BackColor = System.Drawing.Color.White
        TreeNode105.ForeColor = System.Drawing.Color.Black
        TreeNode105.Name = "GroupB_4"
        TreeNode105.Text = "查詢報表"
        TreeNode106.BackColor = System.Drawing.Color.White
        TreeNode106.ForeColor = System.Drawing.Color.Black
        TreeNode106.ImageIndex = 4
        TreeNode106.Name = "AddTransportation"
        TreeNode106.SelectedImageIndex = 4
        TreeNode106.Text = "日報表新增"
        TreeNode107.BackColor = System.Drawing.Color.White
        TreeNode107.ForeColor = System.Drawing.Color.Black
        TreeNode107.ImageIndex = 4
        TreeNode107.Name = "UpdateTransportation"
        TreeNode107.SelectedImageIndex = 4
        TreeNode107.Text = "日報表修改"
        TreeNode108.BackColor = System.Drawing.Color.White
        TreeNode108.ForeColor = System.Drawing.Color.Black
        TreeNode108.ImageIndex = 4
        TreeNode108.Name = "QueryTransportation"
        TreeNode108.SelectedImageIndex = 4
        TreeNode108.Text = "日報表查詢"
        TreeNode109.BackColor = System.Drawing.Color.White
        TreeNode109.ForeColor = System.Drawing.Color.Black
        TreeNode109.ImageIndex = 4
        TreeNode109.Name = "QckUpdateTransPrice"
        TreeNode109.SelectedImageIndex = 4
        TreeNode109.Text = "單價修改"
        TreeNode110.ImageIndex = 4
        TreeNode110.Name = "毛雞預估查詢"
        TreeNode110.SelectedImageIndex = 4
        TreeNode110.Text = "毛雞預估查詢"
        TreeNode111.BackColor = System.Drawing.Color.White
        TreeNode111.ForeColor = System.Drawing.Color.Black
        TreeNode111.Name = "GroupB_5"
        TreeNode111.Text = "毛雞運輸"
        TreeNode112.ImageIndex = 4
        TreeNode112.Name = "QueryPickingItem"
        TreeNode112.SelectedImageIndex = 4
        TreeNode112.Text = "領料查詢"
        TreeNode113.ImageIndex = 4
        TreeNode113.Name = "CalcBomNeeds"
        TreeNode113.SelectedImageIndex = 4
        TreeNode113.Text = "生產需求計算"
        TreeNode114.ImageIndex = 4
        TreeNode114.Name = "_0_01製程基本標準"
        TreeNode114.SelectedImageIndex = 4
        TreeNode114.Text = "製程基本標準"
        TreeNode115.ImageIndex = 4
        TreeNode115.Name = "加工過磅設定"
        TreeNode115.SelectedImageIndex = 4
        TreeNode115.Text = "加工過磅設定"
        TreeNode116.Name = "GroupB_6"
        TreeNode116.Text = "加工作業"
        TreeNode117.ImageIndex = 4
        TreeNode117.Name = "BQuerySRNNotInB1Yet"
        TreeNode117.SelectedImageIndex = 4
        TreeNode117.Text = "生產入庫比對"
        TreeNode118.ImageIndex = 4
        TreeNode118.Name = "時段排程比對_生管"
        TreeNode118.SelectedImageIndex = 4
        TreeNode118.Text = "時段排程比對"
        TreeNode119.ImageIndex = 4
        TreeNode119.Name = "Node9"
        TreeNode119.SelectedImageIndex = 4
        TreeNode119.Text = "即時產成查詢"
        TreeNode120.Name = "GroupB_7"
        TreeNode120.Text = "生產比對"
        TreeNode121.ImageIndex = 4
        TreeNode121.Name = "屠宰記錄"
        TreeNode121.SelectedImageIndex = 4
        TreeNode121.Text = "屠宰記錄"
        TreeNode122.Name = "GroupB_8"
        TreeNode122.Text = "記錄"
        TreeNode123.ImageIndex = 4
        TreeNode123.Name = "分級槽基礎存編設定"
        TreeNode123.SelectedImageIndex = 4
        TreeNode123.Text = "分級槽基礎存編設定"
        TreeNode124.ImageIndex = 4
        TreeNode124.Name = "分級槽基礎存編設定v101"
        TreeNode124.SelectedImageIndex = 4
        TreeNode124.Text = "分級槽基礎存編設定_新"
        TreeNode125.ImageIndex = 4
        TreeNode125.Name = "現場機台過磅設定"
        TreeNode125.SelectedImageIndex = 4
        TreeNode125.Text = "現場機台過磅設定"
        TreeNode126.Name = "GroupB_9"
        TreeNode126.Text = "磅秤設定"
        TreeNode127.BackColor = System.Drawing.Color.White
        TreeNode127.ForeColor = System.Drawing.Color.Black
        TreeNode127.Name = "GroupB"
        TreeNode127.Text = "生管"
        TreeNode128.ImageIndex = 4
        TreeNode128.Name = "SyncInByExcel"
        TreeNode128.SelectedImageIndex = 4
        TreeNode128.Text = "入庫"
        TreeNode129.ImageIndex = 4
        TreeNode129.Name = "SyncOutByExcel"
        TreeNode129.SelectedImageIndex = 4
        TreeNode129.Text = "出庫"
        TreeNode130.Name = "GroupC_1_Excel"
        TreeNode130.Text = "由Excel同步"
        TreeNode131.BackColor = System.Drawing.Color.White
        TreeNode131.ForeColor = System.Drawing.Color.Black
        TreeNode131.Name = "GroupC_1"
        TreeNode131.Text = "同步作業"
        TreeNode132.ImageIndex = 4
        TreeNode132.Name = "入庫自動化"
        TreeNode132.SelectedImageIndex = 4
        TreeNode132.Text = "入庫自動化"
        TreeNode133.ImageIndex = 4
        TreeNode133.Name = "InB1ByManufacture"
        TreeNode133.SelectedImageIndex = 4
        TreeNode133.Text = "生產入庫"
        TreeNode134.ImageIndex = 4
        TreeNode134.Name = "電宰製單入庫"
        TreeNode134.SelectedImageIndex = 4
        TreeNode134.Text = "電宰製單入庫"
        TreeNode135.ImageIndex = 4
        TreeNode135.Name = "InB1BySpecial"
        TreeNode135.SelectedImageIndex = 4
        TreeNode135.Text = "特殊入庫"
        TreeNode136.ImageIndex = 4
        TreeNode136.Name = "InB1ByPurchase"
        TreeNode136.SelectedImageIndex = 4
        TreeNode136.Text = "採購入庫"
        TreeNode137.ImageIndex = 4
        TreeNode137.Name = "採購入庫_鮮享作業"
        TreeNode137.SelectedImageIndex = 4
        TreeNode137.Text = "採購入庫_鮮享作業"
        TreeNode138.ImageIndex = 4
        TreeNode138.Name = "退貨入庫"
        TreeNode138.SelectedImageIndex = 4
        TreeNode138.Text = "退貨入庫"
        TreeNode139.Name = "GroupC_2_In"
        TreeNode139.Text = "入庫"
        TreeNode140.ImageIndex = 4
        TreeNode140.Name = "OutB1"
        TreeNode140.SelectedImageIndex = 4
        TreeNode140.Text = "出庫作業"
        TreeNode141.ImageIndex = 4
        TreeNode141.Name = "QckAddChickenOutOIGE"
        TreeNode141.SelectedImageIndex = 4
        TreeNode141.Text = "毛雞發貨"
        TreeNode142.ImageIndex = 4
        TreeNode142.Name = "出庫作業"
        TreeNode142.SelectedImageIndex = 4
        TreeNode142.Text = "出庫作業_New"
        TreeNode143.Name = "GroupC_2_Out"
        TreeNode143.Text = "出庫"
        TreeNode144.ImageIndex = 4
        TreeNode144.Name = "出庫作業v001"
        TreeNode144.SelectedImageIndex = 4
        TreeNode144.Text = "出庫作業_New2"
        TreeNode145.ImageIndex = 4
        TreeNode145.Name = "QckAddOIGEv5"
        TreeNode145.SelectedImageIndex = 4
        TreeNode145.Text = "生產單快速入出庫"
        TreeNode146.ImageIndex = 4
        TreeNode146.Name = "單據入庫作業"
        TreeNode146.SelectedImageIndex = 4
        TreeNode146.Text = "單據入庫作業"
        TreeNode147.ImageIndex = 4
        TreeNode147.Name = "單據重量列印"
        TreeNode147.SelectedImageIndex = 4
        TreeNode147.Text = "單據重量列印"
        TreeNode148.BackColor = System.Drawing.Color.White
        TreeNode148.ForeColor = System.Drawing.Color.Black
        TreeNode148.Name = "GroupC_2"
        TreeNode148.Text = "回傳B1"
        TreeNode149.ImageIndex = 4
        TreeNode149.Name = "派工查詢"
        TreeNode149.SelectedImageIndex = 4
        TreeNode149.Text = "派工查詢"
        TreeNode150.ImageIndex = 4
        TreeNode150.Name = "分時領料"
        TreeNode150.SelectedImageIndex = 4
        TreeNode150.Text = "分時領料"
        TreeNode151.ImageIndex = 4
        TreeNode151.Name = "分時領料單_生管"
        TreeNode151.SelectedImageIndex = 4
        TreeNode151.Text = "分時領料單"
        TreeNode152.ImageIndex = 4
        TreeNode152.Name = "出急速庫作業"
        TreeNode152.SelectedImageIndex = 4
        TreeNode152.Text = "出急速庫作業"
        TreeNode153.Name = "派工作業"
        TreeNode153.Text = "派工作業"
        TreeNode154.BackColor = System.Drawing.Color.White
        TreeNode154.ForeColor = System.Drawing.Color.Black
        TreeNode154.ImageIndex = 4
        TreeNode154.Name = "ChangeSpace"
        TreeNode154.SelectedImageIndex = 4
        TreeNode154.Text = "條碼儲位變更"
        TreeNode155.BackColor = System.Drawing.Color.White
        TreeNode155.ForeColor = System.Drawing.Color.Black
        TreeNode155.ImageIndex = 4
        TreeNode155.Name = "BatchChangeSpace"
        TreeNode155.SelectedImageIndex = 4
        TreeNode155.Text = "整批儲位變更"
        TreeNode156.BackColor = System.Drawing.Color.White
        TreeNode156.ForeColor = System.Drawing.Color.Black
        TreeNode156.ImageIndex = 4
        TreeNode156.Name = "QueryChangeSpace"
        TreeNode156.SelectedImageIndex = 4
        TreeNode156.Text = "儲位變更查詢"
        TreeNode157.ImageIndex = 4
        TreeNode157.Name = "QueryFromSpace"
        TreeNode157.SelectedImageIndex = 4
        TreeNode157.Text = "查詢儲位條碼調庫記錄"
        TreeNode158.ImageIndex = 4
        TreeNode158.Name = "QueryWplaceStatus"
        TreeNode158.SelectedImageIndex = 4
        TreeNode158.Text = "查詢目前儲位狀況"
        TreeNode159.ImageIndex = 4
        TreeNode159.Name = "調庫作業"
        TreeNode159.SelectedImageIndex = 4
        TreeNode159.Text = "調庫作業"
        TreeNode160.ImageKey = "misamples_blue.gif"
        TreeNode160.Name = "儲位基本資料維護"
        TreeNode160.SelectedImageKey = "misamples_blue.gif"
        TreeNode160.Text = "儲位基本資料維護"
        TreeNode161.BackColor = System.Drawing.Color.White
        TreeNode161.ForeColor = System.Drawing.Color.Black
        TreeNode161.Name = "GroupC_3"
        TreeNode161.Text = "儲位管理"
        TreeNode162.ImageIndex = 4
        TreeNode162.Name = "QuerySRNTradesDetail"
        TreeNode162.SelectedImageIndex = 4
        TreeNode162.Text = "序號交易報表查詢"
        TreeNode163.ImageIndex = 4
        TreeNode163.Name = "QuerySRNStatus"
        TreeNode163.SelectedImageIndex = 4
        TreeNode163.Text = "條碼庫存查詢"
        TreeNode164.ImageIndex = 4
        TreeNode164.Name = "QuerySRNDetail"
        TreeNode164.SelectedImageIndex = 4
        TreeNode164.Text = "依條碼查產品明細資料"
        TreeNode165.ImageIndex = 4
        TreeNode165.Name = "QueryAllocateWplace"
        TreeNode165.SelectedImageIndex = 4
        TreeNode165.Text = "指定入庫查詢表"
        TreeNode166.ImageIndex = 4
        TreeNode166.Name = "QuerySuggestWplace"
        TreeNode166.SelectedImageIndex = 4
        TreeNode166.Text = "指定入庫建議儲位查詢"
        TreeNode167.ImageIndex = 4
        TreeNode167.Name = "QuerySRNFromDraft"
        TreeNode167.SelectedImageIndex = 4
        TreeNode167.Text = "由草稿查詢條碼儲位"
        TreeNode168.BackColor = System.Drawing.Color.White
        TreeNode168.ForeColor = System.Drawing.Color.Black
        TreeNode168.Name = "GroupC_4"
        TreeNode168.Text = "條碼查詢"
        TreeNode169.BackColor = System.Drawing.Color.White
        TreeNode169.ForeColor = System.Drawing.Color.Black
        TreeNode169.ImageIndex = 4
        TreeNode169.Name = "Print_Single"
        TreeNode169.SelectedImageIndex = 4
        TreeNode169.Text = "單張列印"
        TreeNode170.BackColor = System.Drawing.Color.White
        TreeNode170.ForeColor = System.Drawing.Color.Black
        TreeNode170.ImageIndex = 4
        TreeNode170.Name = "Print_Batch"
        TreeNode170.SelectedImageIndex = 4
        TreeNode170.Text = "批次列印"
        TreeNode171.BackColor = System.Drawing.Color.White
        TreeNode171.ForeColor = System.Drawing.Color.Black
        TreeNode171.Name = "GroupC_5"
        TreeNode171.Text = "列印作業"
        TreeNode172.ImageIndex = 4
        TreeNode172.Name = "QueryFIMainStatus"
        TreeNode172.SelectedImageIndex = 4
        TreeNode172.Text = "生產單狀態"
        TreeNode173.ImageIndex = 4
        TreeNode173.Name = "QuerySRNInPDAIn"
        TreeNode173.SelectedImageIndex = 4
        TreeNode173.Text = "條碼狀態"
        TreeNode174.ImageIndex = 4
        TreeNode174.Name = "QuerySRNNotInB1Yet"
        TreeNode174.SelectedImageIndex = 4
        TreeNode174.Text = "生產入庫比對"
        TreeNode175.ImageIndex = 4
        TreeNode175.Name = "QueryFIMainDetail"
        TreeNode175.SelectedImageIndex = 4
        TreeNode175.Text = "生產單明細"
        TreeNode176.ImageIndex = 4
        TreeNode176.Name = "時段排程比對_倉庫"
        TreeNode176.SelectedImageIndex = 4
        TreeNode176.Text = "時段排程比對"
        TreeNode177.Name = "GroupC_6"
        TreeNode177.Text = "製單查詢"
        TreeNode178.ImageIndex = 4
        TreeNode178.Name = "STSForInv"
        TreeNode178.SelectedImageIndex = 4
        TreeNode178.Text = "期末存貨報表"
        TreeNode179.Name = "GroupC_7"
        TreeNode179.Text = "期末存貨報表"
        TreeNode180.ImageIndex = 4
        TreeNode180.Name = "QuickAddOIGE"
        TreeNode180.SelectedImageIndex = 4
        TreeNode180.Text = "快速新增預領單"
        TreeNode181.ImageIndex = 4
        TreeNode181.Name = "QuickAddOIGEv2"
        TreeNode181.SelectedImageIndex = 4
        TreeNode181.Text = "派工單"
        TreeNode182.ImageIndex = 4
        TreeNode182.Name = "QuickAddOIGEv3"
        TreeNode182.SelectedImageIndex = 4
        TreeNode182.Text = "排程領料單"
        TreeNode183.Name = "GroupC_8"
        TreeNode183.Text = "領料單"
        TreeNode184.ImageIndex = 4
        TreeNode184.Name = "Inquiry_001"
        TreeNode184.SelectedImageIndex = 4
        TreeNode184.Text = "冷凍品出庫查詢"
        TreeNode185.ImageIndex = 4
        TreeNode185.Name = "MS223411G"
        TreeNode185.SelectedImageIndex = 4
        TreeNode185.Text = " 現有序號生鮮品(區分庫位)-G備註"
        TreeNode186.ImageIndex = 4
        TreeNode186.Name = "查庫位品項"
        TreeNode186.SelectedImageIndex = 4
        TreeNode186.Text = "查庫位品項"
        TreeNode187.ImageIndex = 4
        TreeNode187.Name = "查詢出庫資料"
        TreeNode187.SelectedImageIndex = 4
        TreeNode187.Text = "查詢出庫資料"
        TreeNode188.ImageIndex = 4
        TreeNode188.Name = "交貨單轉出與轉入"
        TreeNode188.SelectedImageIndex = 4
        TreeNode188.Text = "交貨單轉出與轉入"
        TreeNode189.ImageIndex = 4
        TreeNode189.Name = "採購草稿單入庫"
        TreeNode189.SelectedImageIndex = 4
        TreeNode189.Text = "採購草稿單入庫轉入"
        TreeNode190.ImageIndex = 4
        TreeNode190.Name = "No代工轉入生產"
        TreeNode190.SelectedImageIndex = 4
        TreeNode190.Text = "代工轉入生產"
        TreeNode191.ImageIndex = 4
        TreeNode191.Name = "驗收/領料/加工庫存查詢"
        TreeNode191.SelectedImageIndex = 4
        TreeNode191.Text = "驗收/領料/加工庫存查詢"
        TreeNode192.Name = "GroupC_9"
        TreeNode192.Text = "查詢報表"
        TreeNode193.ImageIndex = 4
        TreeNode193.Name = "倉儲記錄"
        TreeNode193.SelectedImageIndex = 4
        TreeNode193.Text = "倉儲記錄"
        TreeNode194.ImageIndex = 4
        TreeNode194.Name = "倉儲記錄2"
        TreeNode194.SelectedImageIndex = 4
        TreeNode194.Text = "倉儲記錄2"
        TreeNode195.Name = "GroupC_10"
        TreeNode195.Text = "記錄"
        TreeNode196.BackColor = System.Drawing.Color.White
        TreeNode196.ForeColor = System.Drawing.Color.Black
        TreeNode196.Name = "GroupC"
        TreeNode196.Text = "倉庫"
        TreeNode197.ImageIndex = 4
        TreeNode197.Name = "AccMainFrom"
        TreeNode197.SelectedImageIndex = 4
        TreeNode197.Text = "會科餘額明細"
        TreeNode198.ImageIndex = 4
        TreeNode198.Name = "SellToSave"
        TreeNode198.SelectedImageIndex = 4
        TreeNode198.Text = "進銷存"
        TreeNode199.ImageIndex = 4
        TreeNode199.Name = "JournalCheck"
        TreeNode199.SelectedImageIndex = 4
        TreeNode199.Text = "分錄核對"
        TreeNode200.ImageIndex = 4
        TreeNode200.Name = "AccReport"
        TreeNode200.SelectedImageIndex = 4
        TreeNode200.Text = "會科報表"
        TreeNode201.ImageIndex = 4
        TreeNode201.Name = "CompareFrom"
        TreeNode201.SelectedImageIndex = 4
        TreeNode201.Text = "比較表"
        TreeNode202.ImageIndex = 4
        TreeNode202.Name = "CostcoPayment"
        TreeNode202.SelectedImageIndex = 4
        TreeNode202.Text = "關貿請款"
        TreeNode203.ImageIndex = 4
        TreeNode203.Name = "AllJournal"
        TreeNode203.SelectedImageIndex = 4
        TreeNode203.Text = "總分類帳"
        TreeNode204.ImageIndex = 4
        TreeNode204.Name = "ProfitCenter"
        TreeNode204.SelectedImageIndex = 4
        TreeNode204.Text = "利潤中心報表"
        TreeNode205.ImageIndex = 4
        TreeNode205.Name = "發票作廢作業"
        TreeNode205.SelectedImageIndex = 4
        TreeNode205.Text = "發票作廢作業"
        TreeNode206.ImageIndex = 4
        TreeNode206.Name = "發票比對"
        TreeNode206.SelectedImageIndex = 4
        TreeNode206.Text = "發票比對"
        TreeNode207.BackColor = System.Drawing.Color.White
        TreeNode207.ForeColor = System.Drawing.Color.Black
        TreeNode207.Name = "GroupD"
        TreeNode207.Text = "會計"
        TreeNode208.ImageIndex = 4
        TreeNode208.Name = "PaymentForm"
        TreeNode208.SelectedImageIndex = 4
        TreeNode208.Text = "付款申請單"
        TreeNode209.ImageIndex = 4
        TreeNode209.Name = "QckAddOPOR"
        TreeNode209.SelectedImageIndex = 4
        TreeNode209.Text = "快速新增採購草稿"
        TreeNode210.ImageIndex = 4
        TreeNode210.Name = "Node10"
        TreeNode210.SelectedImageIndex = 4
        TreeNode210.Text = "採購歷史資料查詢"
        TreeNode211.ImageIndex = 4
        TreeNode211.Name = "Node11"
        TreeNode211.SelectedImageIndex = 4
        TreeNode211.Text = "毛雞訂購單"
        TreeNode212.BackColor = System.Drawing.Color.White
        TreeNode212.ForeColor = System.Drawing.Color.Black
        TreeNode212.Name = "GroupE"
        TreeNode212.Text = "採購"
        TreeNode213.ImageIndex = 4
        TreeNode213.Name = "屠宰記錄"
        TreeNode213.SelectedImageIndex = 4
        TreeNode213.Text = "屠宰記錄"
        TreeNode214.Name = "GroupSS_1"
        TreeNode214.Text = "生產"
        TreeNode215.ImageIndex = 4
        TreeNode215.Name = "倉儲記錄"
        TreeNode215.SelectedImageIndex = 4
        TreeNode215.Text = "倉儲記錄"
        TreeNode216.ImageIndex = 4
        TreeNode216.Name = "倉儲記錄2"
        TreeNode216.SelectedImageIndex = 4
        TreeNode216.Text = "倉儲記錄2"
        TreeNode217.Name = "GroupSS_2"
        TreeNode217.Text = "倉庫"
        TreeNode218.BackColor = System.Drawing.Color.White
        TreeNode218.ForeColor = System.Drawing.Color.Black
        TreeNode218.Name = "GroupSS"
        TreeNode218.Text = "記錄"
        TreeNode219.ImageIndex = 4
        TreeNode219.Name = "StockApply"
        TreeNode219.SelectedImageIndex = 4
        TreeNode219.Text = "存貨領用申請列表"
        TreeNode220.ImageIndex = 4
        TreeNode220.Name = "Z_Welfare_List"
        TreeNode220.SelectedImageIndex = 4
        TreeNode220.Text = "員購訂單總務覆核"
        TreeNode221.ImageIndex = 4
        TreeNode221.Name = "電話記錄"
        TreeNode221.SelectedImageIndex = 4
        TreeNode221.Text = "電話記錄"
        TreeNode222.ImageIndex = 4
        TreeNode222.Name = "存領單查詢"
        TreeNode222.SelectedImageIndex = 4
        TreeNode222.Text = "存領單查詢"
        TreeNode223.Name = "內部通用"
        TreeNode223.Text = "通用"
        TreeNode224.ImageIndex = 4
        TreeNode224.Name = "訂單自動比對"
        TreeNode224.SelectedImageIndex = 4
        TreeNode224.Text = "訂單自動比對"
        TreeNode225.Name = "內部倉庫"
        TreeNode225.Text = "倉庫"
        TreeNode226.ImageIndex = 4
        TreeNode226.Name = "生管查排程"
        TreeNode226.SelectedImageIndex = 4
        TreeNode226.Text = "生產排程"
        TreeNode227.ImageIndex = 4
        TreeNode227.Name = "計件資料"
        TreeNode227.SelectedImageIndex = 4
        TreeNode227.Text = "計件資料"
        TreeNode228.ImageIndex = 4
        TreeNode228.Name = "磅秤品項現場生管"
        TreeNode228.SelectedImageIndex = 4
        TreeNode228.Text = "磅秤品項設定"
        TreeNode229.ImageIndex = 4
        TreeNode229.Name = "現場磅秤資訊"
        TreeNode229.SelectedImageIndex = 4
        TreeNode229.Text = "現場磅秤資訊"
        TreeNode230.ImageIndex = 4
        TreeNode230.Name = "時段排程比對_現場"
        TreeNode230.SelectedImageIndex = 4
        TreeNode230.Text = "時段排程比對"
        TreeNode231.ImageIndex = 4
        TreeNode231.Name = "產程明細表"
        TreeNode231.SelectedImageIndex = 4
        TreeNode231.Text = "產程明細表"
        TreeNode232.ImageIndex = 4
        TreeNode232.Name = "排程總表"
        TreeNode232.SelectedImageIndex = 4
        TreeNode232.Text = "排程總表"
        TreeNode233.Name = "內部生管"
        TreeNode233.Text = "生管"
        TreeNode234.ImageIndex = 4
        TreeNode234.Name = "薪資計算"
        TreeNode234.SelectedImageIndex = 4
        TreeNode234.Text = "薪資計算"
        TreeNode235.ImageIndex = 4
        TreeNode235.Name = "工時統計"
        TreeNode235.SelectedImageIndex = 4
        TreeNode235.Text = "工時統計"
        TreeNode236.Name = "內部薪資"
        TreeNode236.Text = "薪資"
        TreeNode237.ImageIndex = 4
        TreeNode237.Name = "退貨記錄"
        TreeNode237.SelectedImageIndex = 4
        TreeNode237.Text = "退貨記錄"
        TreeNode238.ImageIndex = 4
        TreeNode238.Name = "檢查記錄"
        TreeNode238.SelectedImageIndex = 4
        TreeNode238.Text = "檢查記錄"
        TreeNode239.ImageIndex = 4
        TreeNode239.Name = "退貨統計"
        TreeNode239.SelectedImageIndex = 4
        TreeNode239.Text = "退貨統計"
        TreeNode240.Name = "內部品管"
        TreeNode240.Text = "品管"
        TreeNode241.ImageIndex = 4
        TreeNode241.Name = "AddTransportation"
        TreeNode241.SelectedImageIndex = 4
        TreeNode241.Text = "日報表新增"
        TreeNode242.ImageIndex = 4
        TreeNode242.Name = "UpdateTransportation"
        TreeNode242.SelectedImageIndex = 4
        TreeNode242.Text = "日報表修改"
        TreeNode243.ImageIndex = 4
        TreeNode243.Name = "QueryTransportation"
        TreeNode243.SelectedImageIndex = 4
        TreeNode243.Text = "日報表查詢"
        TreeNode244.Name = "內部契養"
        TreeNode244.Text = "契養"
        TreeNode245.ImageIndex = 4
        TreeNode245.Name = "健檢數據資料"
        TreeNode245.SelectedImageIndex = 4
        TreeNode245.Text = "健檢數據資料"
        TreeNode246.Name = "內部職安"
        TreeNode246.Text = "職安"
        TreeNode247.BackColor = System.Drawing.Color.White
        TreeNode247.ForeColor = System.Drawing.Color.Black
        TreeNode247.Name = "GroupZ"
        TreeNode247.Text = "內部系統"
        TreeNode248.ImageIndex = 4
        TreeNode248.Name = "過磅基本設定"
        TreeNode248.SelectedImageIndex = 4
        TreeNode248.Text = "過磅基本設定"
        TreeNode249.Name = "基本設定"
        TreeNode249.Text = "基本設定"
        TreeNode250.ImageIndex = 4
        TreeNode250.Name = "員購訂單"
        TreeNode250.SelectedImageIndex = 4
        TreeNode250.Text = "員購訂單"
        TreeNode251.Name = "褔利社系統"
        TreeNode251.Text = "褔利社"
        TreeNode252.ImageIndex = 4
        TreeNode252.Name = "ChangePassWord"
        TreeNode252.SelectedImageIndex = 4
        TreeNode252.Text = "變更密碼"
        Me.MenuTree.Nodes.AddRange(New System.Windows.Forms.TreeNode() {TreeNode28, TreeNode74, TreeNode127, TreeNode196, TreeNode207, TreeNode212, TreeNode218, TreeNode247, TreeNode251, TreeNode252})
        Me.MenuTree.SelectedImageIndex = 2
        Me.MenuTree.ShowLines = False
        Me.MenuTree.Size = New System.Drawing.Size(286, 403)
        Me.MenuTree.TabIndex = 2
        '
        'ImageList1
        '
        Me.ImageList1.ImageStream = CType(resources.GetObject("ImageList1.ImageStream"), System.Windows.Forms.ImageListStreamer)
        Me.ImageList1.TransparentColor = System.Drawing.Color.Transparent
        Me.ImageList1.Images.SetKeyName(0, "xpcollapse1.gif")
        Me.ImageList1.Images.SetKeyName(1, "xpcollapse2.gif")
        Me.ImageList1.Images.SetKeyName(2, "xpexpand1.gif")
        Me.ImageList1.Images.SetKeyName(3, "xpexpand2.gif")
        Me.ImageList1.Images.SetKeyName(4, "misamples_blue.gif")
        '
        'Timer1
        '
        '
        'CompanyDB
        '
        Me.CompanyDB.AutoSize = True
        Me.CompanyDB.Font = New System.Drawing.Font("新細明體", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(136, Byte))
        Me.CompanyDB.Location = New System.Drawing.Point(155, 34)
        Me.CompanyDB.Name = "CompanyDB"
        Me.CompanyDB.Size = New System.Drawing.Size(29, 16)
        Me.CompanyDB.TabIndex = 4
        Me.CompanyDB.Text = "DB"
        '
        'DBSr
        '
        Me.DBSr.AutoSize = True
        Me.DBSr.Font = New System.Drawing.Font("新細明體", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(136, Byte))
        Me.DBSr.Location = New System.Drawing.Point(225, 9)
        Me.DBSr.Name = "DBSr"
        Me.DBSr.Size = New System.Drawing.Size(21, 16)
        Me.DBSr.TabIndex = 5
        Me.DBSr.Text = "Sr"
        '
        'UserName2
        '
        Me.UserName2.AutoSize = True
        Me.UserName2.Font = New System.Drawing.Font("新細明體", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(136, Byte))
        Me.UserName2.Location = New System.Drawing.Point(12, 52)
        Me.UserName2.Name = "UserName2"
        Me.UserName2.Size = New System.Drawing.Size(82, 16)
        Me.UserName2.TabIndex = 12
        Me.UserName2.Text = "UserName2"
        '
        'UserUnit
        '
        Me.UserUnit.AutoSize = True
        Me.UserUnit.Font = New System.Drawing.Font("新細明體", 12.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(136, Byte))
        Me.UserUnit.Location = New System.Drawing.Point(151, 52)
        Me.UserUnit.Name = "UserUnit"
        Me.UserUnit.Size = New System.Drawing.Size(64, 16)
        Me.UserUnit.TabIndex = 13
        Me.UserUnit.Text = "UserUnit"
        '
        '待入庫數提醒時間
        '
        '
        '電話提醒時間
        '
        '
        '待入庫數提醒
        '
        Me.待入庫數提醒.BodyColor = System.Drawing.Color.SteelBlue
        Me.待入庫數提醒.BorderColor = System.Drawing.Color.Navy
        Me.待入庫數提醒.ButtonHoverColor = System.Drawing.Color.Orange
        Me.待入庫數提醒.ContentColor = System.Drawing.Color.Red
        Me.待入庫數提醒.ContentFont = New System.Drawing.Font("Microsoft Sans Serif", 48.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.待入庫數提醒.ContentText = ""
        Me.待入庫數提醒.GradientPower = 1000
        Me.待入庫數提醒.HeaderColor = System.Drawing.Color.Navy
        Me.待入庫數提醒.Image = CType(resources.GetObject("待入庫數提醒.Image"), System.Drawing.Image)
        Me.待入庫數提醒.ImagePosition = New System.Drawing.Point(12, 21)
        Me.待入庫數提醒.ImageSize = New System.Drawing.Size(48, 48)
        Me.待入庫數提醒.LinkHoverColor = System.Drawing.Color.Black
        Me.待入庫數提醒.OptionsMenu = Nothing
        Me.待入庫數提醒.ShowDelay = 1000
        Me.待入庫數提醒.Size = New System.Drawing.Size(800, 600)
        Me.待入庫數提醒.TextPadding = New System.Windows.Forms.Padding(5)
        Me.待入庫數提醒.TitleColor = System.Drawing.Color.White
        Me.待入庫數提醒.TitleFont = New System.Drawing.Font("Microsoft Sans Serif", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.待入庫數提醒.TitleText = ""
        '
        '電話提醒畫面
        '
        Me.電話提醒畫面.BodyColor = System.Drawing.Color.SteelBlue
        Me.電話提醒畫面.BorderColor = System.Drawing.Color.Navy
        Me.電話提醒畫面.ButtonHoverColor = System.Drawing.Color.Orange
        Me.電話提醒畫面.ContentColor = System.Drawing.Color.Red
        Me.電話提醒畫面.ContentFont = New System.Drawing.Font("Microsoft Sans Serif", 48.0!, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.電話提醒畫面.ContentText = ""
        Me.電話提醒畫面.GradientPower = 1000
        Me.電話提醒畫面.HeaderColor = System.Drawing.Color.Navy
        Me.電話提醒畫面.Image = CType(resources.GetObject("電話提醒畫面.Image"), System.Drawing.Image)
        Me.電話提醒畫面.ImagePosition = New System.Drawing.Point(12, 21)
        Me.電話提醒畫面.ImageSize = New System.Drawing.Size(48, 48)
        Me.電話提醒畫面.LinkHoverColor = System.Drawing.Color.Black
        Me.電話提醒畫面.OptionsMenu = Nothing
        Me.電話提醒畫面.ShowDelay = 1000
        Me.電話提醒畫面.Size = New System.Drawing.Size(800, 600)
        Me.電話提醒畫面.TextPadding = New System.Windows.Forms.Padding(5)
        Me.電話提醒畫面.TitleColor = System.Drawing.Color.White
        Me.電話提醒畫面.TitleFont = New System.Drawing.Font("Microsoft Sans Serif", 9.0!, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, CType(0, Byte))
        Me.電話提醒畫面.TitleText = ""
        '
        '即時時間
        '
        '
        'Ck提醒
        '
        Me.Ck提醒.AutoSize = True
        Me.Ck提醒.Location = New System.Drawing.Point(7, 71)
        Me.Ck提醒.Name = "Ck提醒"
        Me.Ck提醒.Size = New System.Drawing.Size(72, 16)
        Me.Ck提醒.TabIndex = 14
        Me.Ck提醒.Text = "開啟提醒"
        Me.Ck提醒.UseVisualStyleBackColor = True
        '
        'MainMenuList
        '
        Me.AutoScaleDimensions = New System.Drawing.SizeF(6.0!, 12.0!)
        Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font
        Me.ClientSize = New System.Drawing.Size(292, 495)
        Me.Controls.Add(Me.Ck提醒)
        Me.Controls.Add(Me.UserUnit)
        Me.Controls.Add(Me.UserName2)
        Me.Controls.Add(Me.DBSr)
        Me.Controls.Add(Me.CompanyDB)
        Me.Controls.Add(Me.GroupBox1)
        Me.Controls.Add(Me.UserName)
        Me.Controls.Add(Me.CompanyName)
        Me.Location = New System.Drawing.Point(5, 5)
        Me.MinimumSize = New System.Drawing.Size(300, 459)
        Me.Name = "MainMenuList"
        Me.ShowIcon = False
        Me.ShowInTaskbar = False
        Me.StartPosition = System.Windows.Forms.FormStartPosition.Manual
        Me.Text = "主功能表"
        Me.GroupBox1.ResumeLayout(False)
        Me.GroupBox1.PerformLayout()
        Me.參數區.ResumeLayout(False)
        Me.參數區.PerformLayout()
        Me.ResumeLayout(False)
        Me.PerformLayout()

    End Sub
    Friend WithEvents CompanyName As System.Windows.Forms.Label
    Friend WithEvents UserName As System.Windows.Forms.Label
    Friend WithEvents GroupBox1 As System.Windows.Forms.GroupBox
    Friend WithEvents Timer1 As System.Windows.Forms.Timer
    Friend WithEvents MenuTree As System.Windows.Forms.TreeView
    Friend WithEvents ImageList1 As System.Windows.Forms.ImageList
    Friend WithEvents CompanyDB As System.Windows.Forms.Label
    Friend WithEvents DBSr As System.Windows.Forms.Label
    Friend WithEvents lbVersion2 As System.Windows.Forms.Label
    Friend WithEvents UserName2 As System.Windows.Forms.Label
    Friend WithEvents UserUnit As System.Windows.Forms.Label
    Friend WithEvents 待入庫數提醒 As PopupNotifier
    Friend WithEvents 待入庫數提醒時間 As System.Windows.Forms.Timer
    Friend WithEvents 參數區 As System.Windows.Forms.GroupBox
    Friend WithEvents 提醒時間s As System.Windows.Forms.Label
    Friend WithEvents 提醒時間2 As System.Windows.Forms.Label
    Friend WithEvents 電話提醒畫面 As PopupNotifier
    Friend WithEvents 電話提醒時間 As System.Windows.Forms.Timer
    Friend WithEvents La時間 As System.Windows.Forms.Label
    Friend WithEvents 即時時間 As System.Windows.Forms.Timer
    Friend WithEvents Button1 As System.Windows.Forms.Button
    Friend WithEvents Ck提醒 As System.Windows.Forms.CheckBox
End Class
